x = input('Digite algo ')
xt = type(x)
print(f'O tipo primitivo desse valor é {xt}')
print('Só tem espaços? {}'.format(x.isspace()))
print('É um número? {}'.format(x.isnumeric()))
print('É alfabético? {}'.format(x.isalpha()))
print('É alfanumérico? {}'.format(x.isalnum()))
print('Está em maiúsculas? {}'.format(x.isupper()))
print('Está em minúsculas? {}'.format(x.islower()))
print('Está capitalizado? {}'.format(x.istitle()))